# This rule is not used by the project powerdns-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the dns.cav.enablers.ob.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: powerdns-operator
    app.kubernetes.io/managed-by: kustomize
  name: pdnsprovider-editor-role
rules:
- apiGroups:
  - dns.cav.enablers.ob
  resources:
  - pdnsproviders
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dns.cav.enablers.ob
  resources:
  - pdnsproviders/status
  verbs:
  - get
